#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Aug 22 15:59:31 2021

@author: dudu
"""

class Talaba:
    def __init__(self, ism, familiya):
        self.ism = ism
        self.familiya = familiya
        self.fanlar = []
    
    def fanga_yozil(self, fan_nomi):
        self.fanlar.append(fan_nomi)
        return self.fanlar
        
class Fan:
    def __init__(self, fan_nomi):
        self.fan_nomi = fan_nomi
    
    def get_info(self):
        return self.fan_nomi
    
        
fan_1 = Fan('matematika')
fan_2 = Fan('Tarix')
talaba_1 = Talaba('Valijon', 'Bozorov')

talaba_1.fanga_yozil(fan_1.get_info())
talaba_1.fanga_yozil(fan_2.get_info())
print(talaba_1.fanlar)